Added support for HTTP Headers
neilco/EventSource pull request #15
Opened 2017-03-03 16:22 UTC by salah-ghanim

2017-04-11 18:01 UTC, neilco requested changes

2017-04-11 18:01 UTC, neilco commented on EventSource/EventSource.h
> ++ (instancetype)eventSourceWithURL:(NSURL *)URL HTTPHeaders:(NSDictionary<NSString*, NSString *>*) headers;
If the `HTTPHeaders` can be `nil`, then add the `nullable` attribute to the parameter. This applies to all the new method signatures in this pull request.

2017-04-11 18:01 UTC, neilco commented on EventSource/EventSource.h
> ++ (instancetype)eventSourceWithURL:(NSURL *)URL HTTPHeaders:(NSDictionary<NSString*, NSString *>*) headers;
Also, style: `NSDictionary<NSString*, NSString *>*` should be `NSDictionary<NSString *, NSString *> *`. This applies to all the new method signatures in this pull request.

2017-04-11 18:01 UTC, neilco commented on EventSource/EventSource.m
> +
Style: Removing the trailing whitespace on this otherwise empty line.

2017-04-11 18:01 UTC, neilco commented on EventSource/EventSource.m
> -
Style: Group together the setting of ivars.

2017-04-11 18:01 UTC, neilco commented on EventSource/EventSource.m
> +        for (NSString * key in self.HTTPRequestHeaders.allKeys){
Style: The preferred style is:

```objc
for (NSString *headerField in self.HTTPRequestHeaders) {
    NSString *value = self.HTTPRequestHeaders[headerField];
    [request setValue:value forHTTPHeaderField:headerField];
}
```

2017-04-13 17:19 UTC, salah-ghanim commented on EventSource/EventSource.h
> ++ (instancetype)eventSourceWithURL:(NSURL *)URL HTTPHeaders:(NSDictionary<NSString*, NSString *>*) headers;
@neilco introducing nullability to the header will introduce warning unless all properties and parameters have nullability attributes

2017-05-15 22:44 UTC, MorganLindqvist commented
This looks like a nice addition, I would like to use it to enable authentication (cookies) for the SSE. Could the outstanding issues be fixed and the pull request landed shortly?

2024-07-15 09:51 UTC, closed without merging